---
- hosts: all
  become: true

  tasks:

    - name: Set hostname
      hostname:
        name: carputer

    - name: Update packages
      apt:
        name: "*"
        state: latest

    - name: Enable USB OTG, UART1 and analog audio
      lineinfile:
        path: /boot/armbianEnv.txt
        regexp: '^overlays='
        line: overlays=usbhost0 uart1 analog-codec
      register: enable_uart

    - name: Reboot after uart enabled
      reboot:
      when: enable_uart.changed

    - name: Install packages
      apt:
        name:
          - python3
          - python3-setuptools
          - python3-pip
          - pulseaudio-module-bluetooth
          - bluez-tools

    - name: Add root user to audio groups
      user:
        name: root
        groups:
          - pulse
          - lp
          - audio

    - name: Add pulse user to audio groups
      user:
        name: pulse
        groups:
          - lp
          - audio

    - name: Enable bluetooth in pulseaudio system mode
      blockinfile:
        path: /etc/pulse/system.pa
        block: |
          .ifexists module-bluetooth-discover.so
          load-module module-bluetooth-discover
          .endif

    - name: Set bluetooth device class to car audio
      lineinfile: 
        path: /etc/bluetooth/main.conf
        regexp: 'Class ='
        line: Class = 0x200420

    - name: Copy systemd definitions
      copy:
        src: files/
        dest: /etc/systemd/system/

    - name: Clone repo on pi
      git:
        repo: https://github.com/nadavami/iAP-to-AVRCP.git
        dest: /root/iAP-to-AVRCP
        depth: 1

    - name: Install pip packages 
      pip:
        requirements: /root/iAP-to-AVRCP/requirements.txt
        executable: /usr/bin/pip3

    - name: Disable wait-online service 
      systemd:
        name: NetworkManager-wait-online.service
        enabled: False

    - name: Start and enable pulseaudio
      systemd:
        name: pulseaudio
        state: started
        enabled: True

    - name: Start and enable bluetooth
      systemd:
        name: bluetooth
        state: started
        enabled: True

    - name: Start and enable bt-agent
      systemd:
        name: bt-agent
        state: started
        enabled: True

    - name: Start and enable iap-to-avrcp
      systemd:
        name: iap-to-avrcp
        state: started
        enabled: True
